# Generated by Django 5.2.3 on 2025-07-07 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_community_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classsection'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Alumni', 'Alumni'), ('Left', 'Left')], default='Active', max_length=10),
        ),
    ]
