# Generated by Django 5.2.3 on 2025-07-23 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_class_name_remove_student_section_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCategory',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('class_name', 'section')},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 5, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(default='2024-2025', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 6, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='bus_route_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('day_scholar', 'Day Scholar'), ('hosteller', 'Hosteller')], default='day_scholar', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('school_bus', 'School Bus'), ('private_van', 'Private Van'), ('auto', 'Auto'), ('own_vehicle', 'Own Vehicle'), ('walk', 'Walk'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='class_teacher',
        ),
    ]
