# Generated by Django 5.2.3 on 2025-07-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_delete_studentcategory_remove_academicyear_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='Optional Biometric ID for fingerprint/iris/face scan', max_length=100, null=True, unique=True),
        ),
    ]
