# Generated by Django 5.2.3 on 2025-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_biometric_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
