# Generated by Django 4.2.22 on 2025-08-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_subject_options_alter_subject_code_and_more'),
        ('students', '0009_studentcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classsection',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.classlevel'),
            preserve_default=False,
        ),
    ]
