# Generated by Django 4.2.22 on 2025-08-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_subject_options_alter_subject_code_and_more'),
        ('students', '0011_alter_classsection_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.classlevel'),
        ),
    ]
