# Generated by Django 4.2.22 on 2025-08-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_classsection_class_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('class_name', 'section')},
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='class_level',
        ),
    ]
