# Generated by Django 4.2.22 on 2025-08-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_examschedule_class_level_and_more'),
        ('students', '0014_classsection_class_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.classlevel'),
        ),
    ]
