# Generated by Django 4.2.22 on 2025-08-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_examschedule_class_level_and_more'),
        ('students', '0015_alter_classsection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.classlevel'),
            preserve_default=False,
        ),
    ]
