# Generated by Django 4.2.22 on 2025-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_classsection_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='section',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='classsection',
            unique_together={('class_name', 'section')},
        ),
        migrations.RemoveField(
            model_name='classsection',
            name='class_level',
        ),
    ]
