# Generated by Django 4.2.22 on 2025-08-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
