# Generated by Django 4.2.22 on 2025-08-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0027_alter_feecategory_applicable_to'),
        ('students', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='fees.studentfeeassignment'),
        ),
    ]
