# Generated by Django 4.2.22 on 2025-08-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_notification_fee_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
