# Generated by Django 4.2.22 on 2025-08-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_student_has_fee_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='has_fee_notification',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_fee_assignment',
        ),
        migrations.DeleteModel(
            name='StudentNotification',
        ),
    ]
