# Generated by Django 5.2.1 on 2025-06-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_category',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('OFFICE', 'Office Staff'), ('DRIVER', 'Driver'), ('CLEANER', 'Sanitary Cleaner'), ('SECURITY', 'Security Guard'), ('ADMIN', 'Administrative / Management'), ('NON_TEACHING', 'Non-Teaching Staff'), ('OTHERS', 'Others')], default='TEACHER', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal / CEO'), ('HR', 'HR / Admin Officer'), ('TEACHER', 'Teacher'), ('OFFICE', 'Office Staff')], default='TEACHER', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
