# Generated by Django 4.2.22 on 2025-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_staff_category_staff_staff_role_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('MATHS', 'Mathematics'), ('ENGLISH', 'English'), ('SOCIAL', 'Social Studies'), ('ACCOUNTS', 'Accounts'), ('OFFICE', 'Office Department'), ('TRANSPORT', 'Transport'), ('OTHERS', 'Others')], default='OTHERS', max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('CLERK', 'Office Clerk'), ('ACCOUNTANT', 'Accountant'), ('DRIVER', 'Driver'), ('SWEEPER', 'Sweeper'), ('GUARD', 'Security Guard'), ('HELPER', 'Helper')], default='TEACHER', max_length=30),
        ),
    ]
