# Generated by Django 4.2.22 on 2025-06-24 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_deleted',
        ),
    ]
