# Generated by Django 5.2.3 on 2025-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
