# Generated by Django 4.2.22 on 2025-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_biometric_id_staff_rfid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='StaffIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('SCIENCE', 'Science'), ('MATHS', 'Mathematics'), ('ENGLISH', 'English'), ('SOCIAL', 'Social Studies'), ('ACCOUNTS', 'Accounts'), ('OFFICE', 'Office Department'), ('TRANSPORT', 'Transport'), ('OTHERS', 'Others')], max_length=30)),
                ('designation', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('TEACHER', 'Teacher'), ('CLERK', 'Office Clerk'), ('ACCOUNTANT', 'Accountant'), ('DRIVER', 'Driver'), ('SWEEPER', 'Sweeper'), ('GUARD', 'Security Guard'), ('HELPER', 'Helper')], max_length=30)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('department', 'designation')},
            },
        ),
    ]
