# Generated by Django 5.2.1 on 2025-06-18 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fees.models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0002_academicyear_studentcategory'),
    ]

    operations = [
        # 1) Create StudentFeeAssignment (FK to existing FeeStructure)
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('original_amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('discount_amount', models.DecimalField(max_digits=10, decimal_places=2, default=0.0)),
                ('final_amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('paid_amount', models.DecimalField(max_digits=10, decimal_places=2, default=0.0)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),

        # 2) FeePayment tweaks (DO NOT add fee_assignment; column exists already)
        migrations.AddField(
            model_name='feepayment',
            name='processed_by',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(max_length=50, unique=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(
                max_length=20,
                choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('NEFT', 'NEFT'), ('Online', 'Online')],
                default='Cash',
            ),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),

        # 3) FeeStructure additions (only those you still need)
        migrations.AddField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(
                to='students.academicyear',
                on_delete=django.db.models.deletion.CASCADE,
                default=fees.models.get_default_academic_year,
            ),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_category',
            field=models.ForeignKey(to='fees.feecategory', on_delete=django.db.models.deletion.CASCADE, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='installments',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_hostel_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_transport_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='medium',
            field=models.CharField(
                max_length=20,
                choices=[('Tamil', 'Tamil'), ('English', 'English')],
                default='English',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feestructure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(),
        ),

        # 4) Final unique_together for FeeStructure
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'class_name', 'medium', 'fee_category')},
        ),
    ]
