# Generated by Django 5.2.3 on 2025-06-27 06:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feestructure_unique_together_and_more'),
        ('students', '0004_alter_student_community_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='notes',
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='medium',
            field=models.CharField(choices=[('English', 'English'), ('Tamil', 'Tamil')], max_length=20),
        ),
        migrations.CreateModel(
            name='FeeConcession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concession_type', models.CharField(max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('send_date', models.DateField(default=django.utils.timezone.now)),
                ('sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('fee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feepayment')),
            ],
        ),
    ]
