# Generated by Django 4.2.22 on 2025-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_remove_feereminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='medium',
            field=models.CharField(choices=[('English', 'English'), ('Tamil', 'Tamil')], default='English', max_length=20),
        ),
    ]
