# Generated by Django 4.2.22 on 2025-08-11 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_feestructure_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='category',
        ),
        migrations.AddField(
            model_name='feecategory',
            name='applicable_to',
            field=models.CharField(choices=[('all', 'All Students'), ('day_scholar', 'Day Scholar'), ('hosteller', 'Hosteller'), ('transport_user', 'Transport User')], default='all', max_length=30),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='fee_type',
            field=models.CharField(choices=[('mandatory', 'Mandatory'), ('optional', 'Optional')], default='mandatory', max_length=10),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='medium',
            field=models.CharField(choices=[('English', 'English'), ('Tamil', 'Tamil')], max_length=20),
        ),
    ]
