# Generated by Django 4.2.22 on 2025-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_remove_feepayment_category_feecategory_applicable_to_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentfeeassignment',
            new_name='fees_studen_student_dc4a4c_idx',
            old_name='fees_studen_student_cf5001_idx',
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='student',
            field=models.CharField(max_length=50),
        ),
    ]
