# Generated by Django 4.2.22 on 2025-08-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('fees', '0007_rename_fees_studen_student_cf5001_idx_fees_studen_student_dc4a4c_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentfeeassignment',
            new_name='fees_studen_student_cf5001_idx',
            old_name='fees_studen_student_dc4a4c_idx',
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
