# Generated by Django 4.2.22 on 2025-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('fees', '0009_alter_studentfeeassignment_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_category',
            field=models.CharField(choices=[('all', 'All Students'), ('day_scholar', 'Day Scholar'), ('hosteller', 'Hosteller'), ('transport_user', 'Transport User')], default='all', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'class_name', 'medium', 'fee_category', 'student_category')},
        ),
    ]
