# Generated by Django 4.2.22 on 2025-08-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('fees', '0010_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('academic_year', 'class_name', 'medium', 'fee_category')},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='student_category',
        ),
    ]
