# Generated by Django 4.2.22 on 2025-08-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
