# Generated by Django 4.2.22 on 2025-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_remove_feestructure_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.CharField(blank=True, choices=[('all', 'All Students'), ('day_scholar', 'Day Scholar'), ('hosteller', 'Hosteller'), ('transport_user', 'Transport User')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
