# Generated by Django 4.2.22 on 2025-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_feestructure_category_feestructure_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='notes',
        ),
    ]
