# Generated by Django 4.2.22 on 2025-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('fees', '0015_remove_feestructure_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
    ]
