# Generated by Django 4.2.22 on 2025-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion
import fees.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('fees', '0016_alter_feestructure_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.ForeignKey(default=fees.models.get_default_academic_year, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
    ]
