# Generated by Django 4.2.22 on 2025-08-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('fees', '0018_alter_feestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
