# Generated by Django 4.2.22 on 2025-08-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0020_alter_feepayment_fee_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.studentfeeassignment'),
        ),
    ]
