# Generated by Django 4.2.22 on 2025-08-13 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0021_alter_feepayment_fee_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
