# Generated by Django 4.2.22 on 2025-08-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0022_alter_feepayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='fees.studentfeeassignment'),
        ),
    ]
