# Generated by Django 4.2.22 on 2025-08-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_classsection_class_name_and_more'),
        ('fees', '0023_alter_feepayment_fee_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_categories', to='students.classsection'),
        ),
    ]
