# Generated by Django 4.2.22 on 2025-08-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0024_feecategory_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecategory',
            name='class_section',
        ),
    ]
