# Generated by Django 4.2.22 on 2025-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0025_remove_feecategory_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecategory',
            name='applicable_to',
            field=models.CharField(default='all', max_length=30),
        ),
    ]
