# Generated by Django 4.2.22 on 2025-08-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_alter_notification_object_id'),
        ('fees', '0027_alter_feecategory_applicable_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='sent', max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Fee SMS History',
                'verbose_name_plural': 'Fee SMS History',
                'ordering': ['-sent_at'],
            },
        ),
    ]
