# Generated by Django 4.2.22 on 2025-08-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0028_feesmshistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feesmshistory',
            table='fees_feesmshistory',
        ),
    ]
