# Generated by Django 4.2.22 on 2025-08-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0029_alter_feesmshistory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feesmshistory',
            table=None,
        ),
    ]
