# Generated by Django 5.2.5 on 2025-09-01 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('students', '0031_alter_notification_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='outpasshistory',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='outpass',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostelpayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='outpass',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'bed_number')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['room'], name='hostel_bed_room_id_9ee754_idx'),
        ),
        migrations.AddIndex(
            model_name='bed',
            index=models.Index(fields=['is_available'], name='hostel_bed_is_avai_8ce865_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='hostel_comp_status_8d9336_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['date_created'], name='hostel_comp_date_cr_0ed870_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelpayment',
            index=models.Index(fields=['hostel'], name='hostel_host_hostel__325a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='outpass',
            index=models.Index(fields=['status'], name='hostel_outp_status_b6bc15_idx'),
        ),
        migrations.AddIndex(
            model_name='outpass',
            index=models.Index(fields=['student'], name='hostel_outp_student_001f89_idx'),
        ),
        migrations.AddIndex(
            model_name='outpasshistory',
            index=models.Index(fields=['created_at'], name='hostel_outp_created_4fc453_idx'),
        ),
        migrations.AddIndex(
            model_name='outpasshistory',
            index=models.Index(fields=['outpass'], name='hostel_outp_outpass_532696_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hostel'], name='hostel_room_hostel__31ffc7_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='hostel_room_room_nu_001bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['hostel'], name='hostel_visi_hostel__50248c_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['visit_date'], name='hostel_visi_visit_d_e60cfb_idx'),
        ),
    ]
