# Generated by Django 4.2.22 on 2025-08-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentcategory'),
        ('exams', '0003_examabsence_examroom_examtype_gradescale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsection'),
        ),
    ]
