# Generated by Django 4.2.22 on 2025-08-13 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_subject_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.classlevel'),
        ),
    ]
