# Generated by Django 4.2.22 on 2025-08-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_subject_options_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'permissions': [('can_manage_subjects', 'Can add/edit subjects')]},
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
