# Generated by Django 4.2.22 on 2025-08-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_classsection_unique_together_and_more'),
        ('exams', '0010_classsection_alter_examschedule_class_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsection'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsection'),
        ),
        migrations.DeleteModel(
            name='ClassSection',
        ),
    ]
