# Generated by Django 4.2.22 on 2025-08-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_classsection_class_name_and_more'),
        ('exams', '0012_classsection_alter_examschedule_class_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.classsection'),
        ),
    ]
