# Generated by Django 4.2.22 on 2025-08-13 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_classsection_class_name_and_more'),
        ('exams', '0013_alter_subject_options_alter_subject_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsection'),
        ),
    ]
