# Generated by Django 5.2.3 on 2025-08-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_biometric_id_staff_rfid_code'),
        ('timetable', '0002_classlevel_alter_period_unique_together_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'staff_role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
